# Generated by Django 6.0.2 on 2026-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('duration', models.IntegerField()),
                ('category', models.CharField(choices=[('development', 'development'), ('testing', 'testing'), ('data analytics', 'data analytics'), ('data science', 'data science'), ('devops', 'devops')], max_length=100)),
                ('image', models.FileField(upload_to='uplodas/')),
            ],
        ),
    ]
