# Generated by Django 6.0 on 2026-03-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_alter_course_rating_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('Data analytics', 'Data analytics'), ('Data science', 'Data science'), ('Devops', 'Devops')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
